#!/usr/bin/env bash
# Run a LOCAL LiveKit SFU on this machine and expose its SIGNALING endpoint to
# the Modal policy server through a Cloudflare quick tunnel.
#
#     robot_sync.py ──ws://127.0.0.1:7880──► local livekit-server ◄──wss tunnel── modal (signaling)
#                                                   ▲
#                                                   └────────── UDP :7882 ◄──────── modal (media+data)
#
# What the tunnel does and does NOT carry (the load-bearing fact):
#   * Cloudflare quick tunnels proxy HTTP/WebSocket ONLY. That covers LiveKit's
#     signaling (join, offer/answer, trickle ICE) — a wss:// URL Modal can dial
#     with zero ports opened here.
#   * WebRTC media AND data channels (the 30fps observation/action loop) are
#     SRTP/SCTP over ICE — UDP, straight from the Modal container to this
#     machine, NOT through Cloudflare. `use_external_ip: true` makes the SFU
#     STUN-discover the public IP and advertise `public_ip:7882` (single-port
#     UDP mux); ICE hole-punches the NAT from both ends. If your router's NAT
#     defeats hole punching (media never flows; see docs/drtc/README.md
#     "Local SFU"),
#     forward UDP 7882 -> this machine and re-run.
#
# First run generates ~/.cache/huggingface/lerobot/livekit.local.yaml (random API
# key/secret) and every run writes ~/.cache/huggingface/lerobot/livekit.local.env
# so the ROBOT side automatically targets the local SFU
# (makermodslab.drtc._env.load_env loads it with override=True). Delete
# livekit.local.env to point the robot back at LiveKit Cloud. NOTE: it outlives
# this script — after Ctrl-C the robot keeps dialing ws://127.0.0.1:7880 and gets
# connection refused until you restart this script or delete the file.
#
# Requires: livekit-server, cloudflared (both: `brew install livekit cloudflared`).
set -euo pipefail
# All generated state lives beside the rest of MakerMods Lab's persistent state
# (see makermodslab/utils/config.py: DRTC_SFU_CONFIG_PATH / DRTC_LOCAL_ENV_PATH /
# DRTC_LOG_DIR), NOT next to this script, so the robot side can be started from
# any directory — makermodslab.drtc._env.load_env reads the override from there.
STATE_DIR="${HOME}/.cache/huggingface/lerobot"
LOG_DIR="${STATE_DIR}/logs/drtc"
REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

CONFIG="${STATE_DIR}/livekit.local.yaml"
ROBOT_ENV="${STATE_DIR}/livekit.local.env"
SIGNAL_PORT=7880
TCP_PORT=7881   # ICE/TCP fallback (only reachable on the LAN; harmless to keep)
UDP_PORT=7882   # single-port UDP mux — the ONE port to forward if NAT blocks media
TS=$(date +%s)
mkdir -p "$LOG_DIR"

# --- one-time local credentials ---------------------------------------------
if [[ ! -f "$CONFIG" ]]; then
    KEY="local-$(openssl rand -hex 4)"
    SECRET="$(openssl rand -hex 32)"   # livekit requires >= 32 chars
    cat > "$CONFIG" <<EOF
# Generated by tools/drtc/local_sfu.sh ($(date -u +%Y-%m-%dT%H:%M:%SZ)).
# Delete this file to rotate the local API key/secret.
port: ${SIGNAL_PORT}
rtc:
  udp_port: ${UDP_PORT}
  tcp_port: ${TCP_PORT}
  use_external_ip: true
keys:
  ${KEY}: ${SECRET}
EOF
    echo "[local_sfu] generated $CONFIG (new local key/secret)"
fi
KEY=$(awk '/^keys:/{getline; gsub(/[: ]+$/,"",$1); print $1; exit}' "$CONFIG" | tr -d ':')
SECRET=$(awk '/^keys:/{getline; print $2; exit}' "$CONFIG")

# --- point the robot side at the local SFU -----------------------------------
cat > "$ROBOT_ENV" <<EOF
# Generated by tools/drtc/local_sfu.sh — routes the ROBOT side to the local SFU.
# Loaded with override=True by makermodslab.drtc._env.load_env; LIVEKIT_ROOM
# still comes from livekit.env. DELETE this file to go back to LiveKit Cloud.
LIVEKIT_URL=ws://127.0.0.1:${SIGNAL_PORT}
LIVEKIT_API_KEY=${KEY}
LIVEKIT_API_SECRET=${SECRET}
EOF

# --- start SFU + tunnel ------------------------------------------------------
SFU_LOG="${LOG_DIR}"/local_sfu_${TS}.log
CF_LOG="${LOG_DIR}"/cloudflared_${TS}.log

livekit-server --config "$CONFIG" >"$SFU_LOG" 2>&1 &
SFU_PID=$!
cloudflared tunnel --url "http://127.0.0.1:${SIGNAL_PORT}" --no-autoupdate >"$CF_LOG" 2>&1 &
CF_PID=$!
trap 'echo; echo "[local_sfu] shutting down"; kill $SFU_PID $CF_PID 2>/dev/null; wait 2>/dev/null' EXIT INT TERM

# SFU up?
for _ in $(seq 1 20); do
    curl -sf "http://127.0.0.1:${SIGNAL_PORT}" >/dev/null 2>&1 && break
    kill -0 $SFU_PID 2>/dev/null || { echo "[local_sfu] livekit-server died — see $SFU_LOG"; exit 1; }
    sleep 0.5
done

# Quick tunnel assigned? (cloudflared prints the random trycloudflare.com URL)
TUNNEL_URL=""
for _ in $(seq 1 60); do
    TUNNEL_URL=$(grep -oE 'https://[a-z0-9-]+\.trycloudflare\.com' "$CF_LOG" | head -1 || true)
    [[ -n "$TUNNEL_URL" ]] && break
    kill -0 $CF_PID 2>/dev/null || { echo "[local_sfu] cloudflared died — see $CF_LOG"; exit 1; }
    sleep 0.5
done
[[ -n "$TUNNEL_URL" ]] || { echo "[local_sfu] no tunnel URL after 30s — see $CF_LOG"; exit 1; }
WSS_URL="wss://${TUNNEL_URL#https://}"

echo
echo "[local_sfu] SFU:    ws://127.0.0.1:${SIGNAL_PORT}  (pid $SFU_PID, log $SFU_LOG)"
echo "[local_sfu] tunnel: ${WSS_URL}  (pid $CF_PID, log $CF_LOG)"
echo "[local_sfu] robot side: python -m makermodslab.drtc.robot_sync (or robot_rtc) from anywhere — $ROBOT_ENV now targets the local SFU"
echo
echo "[local_sfu] Modal side (quick-tunnel URL changes every launch — rerun with fresh flags):"
echo
echo "    modal run ${REPO_ROOT}/makermodslab/drtc/modal_policy.py --policy-path \${HF_USER}/my_policy --horizon 16 \\"
echo "        --livekit-url ${WSS_URL} \\"
echo "        --livekit-api-key ${KEY} --livekit-api-secret ${SECRET}"
echo
echo "[local_sfu] Ctrl-C to stop both."
wait
