import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import {
  ENERGIZING_DEVICE_ACTIONS,
  ENERGIZING_SESSION_KINDS,
  RELEASE_ACTIONS,
  ROBOT_ACTIONS,
} from "@/lib/robotActions";
import en from "@/i18n/locales/en";

/**
 * The amber "this drives the arm" treatment must cover exactly the session
 * kinds the backend can actually start. The committed OpenAPI snapshot is the
 * contract (regenerated by makermodslab.scripts.export_openapi and enforced
 * fresh by the Python suite), so reading the enum out of it means a new
 * backend kind fails HERE — at the point where its start button would ship
 * unmarked — instead of quietly rendering as an ordinary button.
 */
const OPENAPI_PATH = join(process.cwd(), "..", "docs", "api", "openapi.json");

function backendStartableKinds(): string[] {
  const doc = JSON.parse(readFileSync(OPENAPI_PATH, "utf8")) as {
    components?: {
      schemas?: Record<string, { properties?: Record<string, unknown> }>;
    };
  };
  const kind = doc.components?.schemas?.SessionStartBody?.properties?.kind as
    | { enum?: unknown }
    | undefined;
  const values = kind?.enum;
  // A snapshot that stopped enumerating the kinds would make this test pass
  // vacuously, so treat that as the failure it is rather than skipping.
  if (!Array.isArray(values) || values.length === 0) {
    throw new Error(
      `SessionStartBody.properties.kind.enum is missing or empty in ${OPENAPI_PATH}`,
    );
  }
  return values.map(String);
}

describe("robot action map", () => {
  it("marks exactly the backend's startable session kinds as energizing", () => {
    expect([...ENERGIZING_SESSION_KINDS].sort()).toEqual(
      backendStartableKinds().sort(),
    );
  });

  it("gives every energizing action the amber robot treatment", () => {
    for (const key of [
      ...ENERGIZING_SESSION_KINDS,
      ...ENERGIZING_DEVICE_ACTIONS,
    ]) {
      expect(ROBOT_ACTIONS[key].treatment, key).toBe("robot");
    }
  });

  it("gives every release action the destructive treatment", () => {
    for (const key of RELEASE_ACTIONS) {
      expect(ROBOT_ACTIONS[key].treatment, key).toBe("destructive");
    }
  });

  it("covers every action and nothing else", () => {
    expect(Object.keys(ROBOT_ACTIONS).sort()).toEqual(
      [
        ...ENERGIZING_SESSION_KINDS,
        ...ENERGIZING_DEVICE_ACTIONS,
        ...RELEASE_ACTIONS,
      ].sort(),
    );
  });

  it("points every action at a tooltip key that exists in the catalog", () => {
    const tooltips = en.shared.robotAction.tooltip as Record<string, string>;
    for (const [key, spec] of Object.entries(ROBOT_ACTIONS)) {
      const leaf = spec.tooltipKey.split(".").pop() as string;
      expect(
        tooltips[leaf],
        `${key} → ${spec.tooltipKey}`,
      ).toBeTruthy();
    }
  });
});
